//
//  SorterTests.swift
//  MovielixTests
//
//  Created by Mustafa Ezzat on 5/8/20.
//  Copyright © 2020 Swvl. All rights reserved.
//

@testable import Movielix

enum ConstantTests {
    static let movies =  [Movie(title: "As Above, So Below", year: 2014, cast: ["Perdita Weeks", "Ben Feldman", "Edwin Hodge", "François Civil"], genres: ["Horror"], rating: 2), Movie(title: "I Melt with You", year: 2011, cast: ["Thomas Jane", "Jeremy Piven", "Rob Lowe", "Christian McKay", "Carla Gugino", "Tom Bower", "Arielle Kebbel", "Sasha Grey"], genres: ["Thriller"], rating: 1), Movie(title: "Jay & Silent Bob\'s Super Groovy Cartoon Movie", year: 2013, cast: ["Jason Mewes", "Kevin Smith", "Eliza Dushku", "Tara Strong", "Ralph Garman", "Neil Gaiman"], genres: ["Animated", "Comedy"], rating: 4), Movie(title: "Fahrenheit 11/9", year: 2018, cast: [], genres: ["Documentary"], rating: 5), Movie(title: "Higher Ground", year: 2011, cast: ["Vera Farmiga", "Joshua Leonard", "Norbert Leo Butz", "Dagmara Dominczyk", "John Hawkes", "Bill Irwin", "Ebon Moss-Bachrach", "Donna Murphy"], genres: ["Drama"], rating: 3), Movie(title: "Red Tails", year: 2012, cast: ["Cuba Gooding, Jr.", "Terrence Howard", "Daniela Ruah", "Bryan Cranston", "Nate Parker", "David Oyelowo", "Ryan Early", "Method Man", "Elijah Kelley", "Ne-Yo", "Tristan Wilds", "Kevin Phillips", "Robert Kazinsky", "Lee Tergesen", "Andre Royo", "Marcus T. Paulk", "Michael B. Jordan"], genres: ["Action", "Drama", "War"], rating: 4), Movie(title: "Saving Santa", year: 2013, cast: ["Martin Freeman", "Tim Curry", "Noel Clarke", "Tim Conway", "Pam Ferris"], genres: ["Animated"], rating: 1), Movie(title: "Boo! A Madea Halloween", year: 2016, cast: ["Tyler Perry"], genres: [], rating: 2), Movie(title: "The One I Love", year: 2014, cast: ["Mark Duplass", "Ted Danson", "Elisabeth Moss"], genres: ["Romance", "Comedy"], rating: 5)]

    static let sortedMovies = [Movie(title: "Fahrenheit 11/9", year: 2018, cast: [], genres: ["Documentary"], rating: 5), Movie(title: "The One I Love", year: 2014, cast: ["Mark Duplass", "Ted Danson", "Elisabeth Moss"], genres: ["Romance", "Comedy"], rating: 5), Movie(title: "Jay & Silent Bob\'s Super Groovy Cartoon Movie", year: 2013, cast: ["Jason Mewes", "Kevin Smith", "Eliza Dushku", "Tara Strong", "Ralph Garman", "Neil Gaiman"], genres: ["Animated", "Comedy"], rating: 4), Movie(title: "Red Tails", year: 2012, cast: ["Cuba Gooding, Jr.", "Terrence Howard", "Daniela Ruah", "Bryan Cranston", "Nate Parker", "David Oyelowo", "Ryan Early", "Method Man", "Elijah Kelley", "Ne-Yo", "Tristan Wilds", "Kevin Phillips", "Robert Kazinsky", "Lee Tergesen", "Andre Royo", "Marcus T. Paulk", "Michael B. Jordan"], genres: ["Action", "Drama", "War"], rating: 4), Movie(title: "Higher Ground", year: 2011, cast: ["Vera Farmiga", "Joshua Leonard", "Norbert Leo Butz", "Dagmara Dominczyk", "John Hawkes", "Bill Irwin", "Ebon Moss-Bachrach", "Donna Murphy"], genres: ["Drama"], rating: 3), Movie(title: "As Above, So Below", year: 2014, cast: ["Perdita Weeks", "Ben Feldman", "Edwin Hodge", "François Civil"], genres: ["Horror"], rating: 2), Movie(title: "Boo! A Madea Halloween", year: 2016, cast: ["Tyler Perry"], genres: [], rating: 2), Movie(title: "I Melt with You", year: 2011, cast: ["Thomas Jane", "Jeremy Piven", "Rob Lowe", "Christian McKay", "Carla Gugino", "Tom Bower", "Arielle Kebbel", "Sasha Grey"], genres: ["Thriller"], rating: 1), Movie(title: "Saving Santa", year: 2013, cast: ["Martin Freeman", "Tim Curry", "Noel Clarke", "Tim Conway", "Pam Ferris"], genres: ["Animated"], rating: 1)]
    
    static let categorizedMovies = [YearMives(year: 2018, movies: [Movie(title: "Fahrenheit 11/9", year: 2018, cast: [], genres: ["Documentary"], rating: 5)]), YearMives(year: 2016, movies: [Movie(title: "Boo! A Madea Halloween", year: 2016, cast: ["Tyler Perry"], genres: [], rating: 2)]), YearMives(year: 2014, movies: [Movie(title: "The One I Love", year: 2014, cast: ["Mark Duplass", "Ted Danson", "Elisabeth Moss"], genres: ["Romance", "Comedy"], rating: 5), Movie(title: "As Above, So Below", year: 2014, cast: ["Perdita Weeks", "Ben Feldman", "Edwin Hodge", "François Civil"], genres: ["Horror"], rating: 2)]), YearMives(year: 2013, movies: [Movie(title: "Jay & Silent Bob\'s Super Groovy Cartoon Movie", year: 2013, cast: ["Jason Mewes", "Kevin Smith", "Eliza Dushku", "Tara Strong", "Ralph Garman", "Neil Gaiman"], genres: ["Animated", "Comedy"], rating: 4), Movie(title: "Saving Santa", year: 2013, cast: ["Martin Freeman", "Tim Curry", "Noel Clarke", "Tim Conway", "Pam Ferris"], genres: ["Animated"], rating: 1)]), YearMives(year: 2012, movies: [Movie(title: "Red Tails", year: 2012, cast: ["Cuba Gooding, Jr.", "Terrence Howard", "Daniela Ruah", "Bryan Cranston", "Nate Parker", "David Oyelowo", "Ryan Early", "Method Man", "Elijah Kelley", "Ne-Yo", "Tristan Wilds", "Kevin Phillips", "Robert Kazinsky", "Lee Tergesen", "Andre Royo", "Marcus T. Paulk", "Michael B. Jordan"], genres: ["Action", "Drama", "War"], rating: 4)]), YearMives(year: 2011, movies: [Movie(title: "Higher Ground", year: 2011, cast: ["Vera Farmiga", "Joshua Leonard", "Norbert Leo Butz", "Dagmara Dominczyk", "John Hawkes", "Bill Irwin", "Ebon Moss-Bachrach", "Donna Murphy"], genres: ["Drama"], rating: 3), Movie(title: "I Melt with You", year: 2011, cast: ["Thomas Jane", "Jeremy Piven", "Rob Lowe", "Christian McKay", "Carla Gugino", "Tom Bower", "Arielle Kebbel", "Sasha Grey"], genres: ["Thriller"], rating: 1)])]
    
    static let prefixMovieWithTheOne = [YearMives(year: 2014, movies: [Movie(title: "The One I Love", year: 2014, cast: ["Mark Duplass", "Ted Danson", "Elisabeth Moss"], genres: ["Romance", "Comedy"], rating: 5)])]
    
    static let postfixMovieWithMadeaHalloween = [YearMives(year: 2016, movies: [Movie(title: "Boo! A Madea Halloween", year: 2016, cast: ["Tyler Perry"], genres: [], rating: 2)])]
    
    static let infixMovieBobSuperGroovy = [YearMives(year: 2013, movies: [Movie(title: "Jay & Silent Bob\'s Super Groovy Cartoon Movie", year: 2013, cast: ["Jason Mewes", "Kevin Smith", "Eliza Dushku", "Tara Strong", "Ralph Garman", "Neil Gaiman"], genres: ["Animated", "Comedy"], rating: 4)])]
}
