excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - MovielixTests/ModulesTests/Helpers/ConstantTests.swift
  # rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 160
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
