# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Movielix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movielix
  pod 'Moya'
  pod 'lottie-ios'
  pod 'Cosmos'
  pod 'Nuke'
  pod 'Unrealm'
  pod 'SwiftLint'

  target 'MovielixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovielixUITests' do
    # Pods for testing
  end

end
