# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movielix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movielix
  pod 'lottie-ios'

  target 'MovielixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovielixUITests' do
    # Pods for testing
  end

end
